name: Upload Excel File to Qualer

on:
  pull_request:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout shared CI scripts
        uses: actions/checkout@v3
        with:
          repository: Johnson-Gage-Inspection-Inc/ci-scripts
          path: ci-scripts
          fetch-depth: 0

      - name: Fetch all history for comparison
        run: git fetch --prune --unshallow

      - name: Debug Git History
        run: |
          echo "Current branch:"
          git branch
          echo "Last 5 commits:"
          git log --oneline -5

      - name: Locate Changed Excel File
        id: changed-file
        uses: tj-actions/changed-files@v35
        with:
          files: '**/*.xlsx'
          fetch-depth: 0

      - name: Skip workflow if no Excel files were modified
        if: steps.changed-file.outputs.any_changed == 'false'
        run: |
          echo "✅ No Excel files changed. Skipping Qualer upload."
          exit 0

      - name: Ensure Only One File is Changed
        if: steps.changed-file.outputs.any_changed == 'true'
        run: |
          FILE_COUNT=$(echo "${{ steps.changed-file.outputs.all_changed_files }}" | wc -w)
          if [ "$FILE_COUNT" -ne 1 ]; then
            echo "❌ Error: More than one Excel file was changed. Only one file is allowed per PR."
            exit 1
          fi
          echo "MERGED_FILE=${{ steps.changed-file.outputs.all_changed_files }}" >> $GITHUB_ENV

      - name: Upload Excel File to Qualer
        if: steps.changed-file.outputs.any_changed == 'true'
        run: ./ci-scripts/upload_sop.sh
        env:
          QUALER_EMAIL: ${{ secrets.QUALER_EMAIL }}
          QUALER_PASSWORD: ${{ secrets.QUALER_PASSWORD }}
          SOP_ID: 2420
          MERGED_FILE: ${{ env.MERGED_FILE }}
